server:
  host: 0.0.0.0
  port: 8080
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 10240

spring:
  servlet:
    multipart:
      max-file-size: 102400KB
      max-request-size: 102400KB
  mvc:
    async:
      request-timeout: 40000
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ${DB_POOL_NAME:ivms_service}
      minimum-idle: ${DB_MIN_IDLE_CONNECTION:1}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
      max-lifetime: ${DB_POOL_MAX_LIFETIME:1800000}
      idle-timeout: ${DB_POOL_IDLE_TIMEOUT:30000}

management:
  endpoints:
    web:
      exposure:
        include: loggers, health
  loggers:
    enabled: true
  health:
    enabled: true
    diskspace:
      threshold: ${DISK_SPACE_THRESHOLD:0}
      enabled: true

ivms_old_service_base_url: abc